export const ERROR_404 = '404';

export const CART_ACTIONS = {
  OPEN: 'OPEN',
  CLOSE: 'CLOSE',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CHANGE_ITEM: 'CHANGE_ITEM',
  FETCH_BEGINS: 'FETCH_BEGINS',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_FAILURE: 'FETCH_FAILURE'
}