export const ERROR_ACTIONS = {
  BAD_REQUEST: 'BAD_REQUEST_ERROR',
  NOT_FOUND: 'NOT_FOUND_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

export const CART_ACTIONS = {
  OPEN: 'OPEN_CART',
  CLOSE: 'CLOSE_CART',
  UPDATE_ITEMS: 'UPDATE_ITEMS_CART',
  FETCH_BEGINS: 'FETCH_BEGINS_CART',
  FETCH_SUCCESS: 'FETCH_SUCCESS_CART',
  FETCH_FAILURE: 'FETCH_FAILURE_CART'
}

export const FILTER_ACTIONS = {
  BRANDS: 'BRANDS_FILTER',
  SIZES: 'SIZES_FILTER',
  MAXPRICE: 'MAXPRICE_FILTER',
  MINPRICE: 'MINPRICE_FILTER',
  CATEGORY: 'CATEGORY_FILTER',
};