export const FAVORITES_ACTIONS = {
  UPDATE_ITEMS: 'UPDATE_ITEMS_FAVORITES',
  FETCH_BEGINS: 'FETCH_BEGINS_FAVORITES',
  FETCH_SUCCESS: 'FETCH_SUCCESS_FAVORITES',
  FETCH_FAILURE: 'FETCH_FAILURE_FAVORITES'
};
