export const FILTER_ACTIONS = {
  BRANDS: 'BRANDS_FILTER',
  SIZES: 'SIZES_FILTER',
  MAXPRICE: 'MAXPRICE_FILTER',
  MINPRICE: 'MINPRICE_FILTER',
  CATEGORY: 'CATEGORY_FILTER',
  SEARCH: 'SEARCH_FILTER',
  CLEAR: 'CLEAR_FILTER',
  SET_INITIAL_STATE: 'SET_STATE_FILTER',
};